// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientManagement.Models.Contexts;

#nullable disable

namespace PatientManagement.Migrations
{
    [DbContext(typeof(PatientContext))]
    [Migration("20240225103721_PrescriptionToManyVisitsEachPrescriptionValueUnique")]
    partial class PrescriptionToManyVisitsEachPrescriptionValueUnique
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.26");

            modelBuilder.Entity("HistoryVisit", b =>
                {
                    b.Property<string>("HistoriesId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitsId")
                        .HasColumnType("TEXT");

                    b.HasKey("HistoriesId", "VisitsId");

                    b.HasIndex("VisitsId");

                    b.ToTable("HistoryVisit");
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.History", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryHeadingId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HistoryHeadingId");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.HistoryHeading", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("HistoryHeadings");
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.Patient", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT COLLATE NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Gender", "Age")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.Visit", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionalDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Visits");
                });

            modelBuilder.Entity("PatientManagement.Models.Prescription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrescriptionValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionValue")
                        .IsUnique();

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("PrescriptionVisit", b =>
                {
                    b.Property<string>("PrescriptionsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VisitsId")
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionsId", "VisitsId");

                    b.HasIndex("VisitsId");

                    b.ToTable("PrescriptionVisit");
                });

            modelBuilder.Entity("HistoryVisit", b =>
                {
                    b.HasOne("PatientManagement.Models.DataEntites.History", null)
                        .WithMany()
                        .HasForeignKey("HistoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientManagement.Models.DataEntites.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.History", b =>
                {
                    b.HasOne("PatientManagement.Models.DataEntites.HistoryHeading", "HistoryHeading")
                        .WithMany("History")
                        .HasForeignKey("HistoryHeadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryHeading");
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.Visit", b =>
                {
                    b.HasOne("PatientManagement.Models.DataEntites.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PrescriptionVisit", b =>
                {
                    b.HasOne("PatientManagement.Models.Prescription", null)
                        .WithMany()
                        .HasForeignKey("PrescriptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatientManagement.Models.DataEntites.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientManagement.Models.DataEntites.HistoryHeading", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
